export const SIDEBAR_TOOL_BUTTONS = [
    { service: 'PencilService', name: 'Crayon', icon: 'assets/sidebar-icons/pencil.svg', keyShortcut: 'c', helpShortcut: '(Touche C)' },
    { service: 'RectangleService', name: 'Rectangle', icon: 'assets/sidebar-icons/rectangle.svg', keyShortcut: '1', helpShortcut: '(Touche 1)' },
    { service: 'PolygoneService', name: 'Polygone', icon: 'assets/sidebar-icons/polygon.svg', keyShortcut: '3', helpShortcut: '(Touche 3)' },
    {
        service: 'RectangleSelectionService',
        name: 'Rectangle de Selection',
        icon: 'assets/sidebar-icons/selection-rect.svg',
        keyShortcut: 'r',
        helpShortcut: '(Touche R)',
    },
    {
        service: 'LassoSelectionService',
        name: 'Lasso polygonal',
        icon: 'assets/sidebar-icons/polygonal-lasso.svg',
        keyShortcut: 'v',
        helpShortcut: '(Touche V)',
    },
    { service: 'StampService', name: 'Étampe', icon: 'assets/sidebar-icons/stamp.svg', keyShortcut: 'd', helpShortcut: '(Touche D)' },
    { service: 'PipetteService', name: 'Pipette', icon: 'assets/sidebar-icons/eyedroper.svg', keyShortcut: 'i', helpShortcut: '(Touche I)' },
    { service: 'EraserService', name: 'Efface', icon: 'assets/sidebar-icons/eraser.svg', keyShortcut: 'e', helpShortcut: '(Touche E)' },
    { service: 'EllipseService', name: 'Ellipse', icon: 'assets/sidebar-icons/ellipse.svg', keyShortcut: '2', helpShortcut: '(Touche 2)' },
    { service: 'LineService', name: 'Ligne', icon: 'assets/sidebar-icons/line.svg', keyShortcut: 'l', helpShortcut: '(Touche L)' },
    {
        service: 'EllipseSelectionService',
        name: 'Ellipse de selection',
        icon: 'assets/sidebar-icons/selection-ellipse.svg',
        keyShortcut: 's',
        helpShortcut: '(Touche S)',
    },
    { service: 'TextService', name: 'Texte', icon: 'assets/sidebar-icons/text.svg', keyShortcut: 't', helpShortcut: '(Touche T)' },
    { service: 'AerosolService', name: 'Aérosol', icon: 'assets/sidebar-icons/spray.svg', keyShortcut: 'a', helpShortcut: '(Touche A)' },
    {
        service: 'PaintBucketService',
        name: 'Sceau de peinture',
        icon: 'assets/sidebar-icons/bucket.svg',
        keyShortcut: 'b',
        helpShortcut: '(Touche B)',
    },
];
